
# .goreleaser.yml
before:
    hooks:
        - go mod download

builds:
    -
        id: "fls-check"
        dir: ./fls-check
        main: ./main.go
        binary: fls-check-plugin

archives:
    -
        builds:
            - fls-check
        replacements:
            amd64: 64-bit
            386: 32-bit
            darwin: macOS